### ISSUE TITLE
New Version 

### ISSUE THREAD

**Issue by Heater711** [b1naryth1ef/sneaker#4]
Server is now Running, [Here ](https://hoggit.brrt.me/servers/gaw) I see the Scratch Pad and Draw. Is there a new version about this repo ?

BTW, on Windows everything looks good! 
![sneaker3](https://user-images.githubusercontent.com/72864507/134938286-4d7e7e6e-7807-4c89-8c1f-14e71c3ace44.png)

**Comment by b1naryth1ef** [comment]
I'm in the middle of some more complex changes so gonna hold off on pushing a new release with just the draw / scratchpad features since those are new and mostly unfinished. If you'd like to run the testing version its available here: https://buildyboi.ci/api/artifact/357/download/sneaker-windows-amd64-testing (note: you will need to rename and add on `.exe`)

**Comment by Heater711** [comment]
Tested. Not working good, I guess

![sneaker4](https://user-images.githubusercontent.com/72864507/134978228-c6281864-6f4d-4261-95de-335058159867.png)

**Comment by b1naryth1ef** [comment]
https://github.com/b1naryth1ef/sneaker/releases/tag/v0.0.3

**Comment by Heater711** [comment]
v0.0.3 not working. Webpage show "Not Found"

**Comment by b1naryth1ef** [comment]
@Heater711 Apologies, this took someone else trying it on Windows for me to realize this was a platform specific issue. Can you please test out [v0.0.4](https://github.com/b1naryth1ef/sneaker/releases/tag/v0.0.4) which should fix this?
